# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/g10

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/g10

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/g10/CMakeFiles /mnt/g10//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/g10/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named wiscAFS_server

# Build rule for target.
wiscAFS_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wiscAFS_server
.PHONY : wiscAFS_server

# fast build rule for target.
wiscAFS_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS_server.dir/build.make CMakeFiles/wiscAFS_server.dir/build
.PHONY : wiscAFS_server/fast

#=============================================================================
# Target rules for targets named wiscAFS

# Build rule for target.
wiscAFS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wiscAFS
.PHONY : wiscAFS

# fast build rule for target.
wiscAFS/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/build
.PHONY : wiscAFS/fast

conf.o: conf.c.o
.PHONY : conf.o

# target to build an object file
conf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/conf.c.o
.PHONY : conf.c.o

conf.i: conf.c.i
.PHONY : conf.i

# target to preprocess a source file
conf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/conf.c.i
.PHONY : conf.c.i

conf.s: conf.c.s
.PHONY : conf.s

# target to generate assembly for a file
conf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/conf.c.s
.PHONY : conf.c.s

connect_grpc_fuse.o: connect_grpc_fuse.cpp.o
.PHONY : connect_grpc_fuse.o

# target to build an object file
connect_grpc_fuse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/connect_grpc_fuse.cpp.o
.PHONY : connect_grpc_fuse.cpp.o

connect_grpc_fuse.i: connect_grpc_fuse.cpp.i
.PHONY : connect_grpc_fuse.i

# target to preprocess a source file
connect_grpc_fuse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/connect_grpc_fuse.cpp.i
.PHONY : connect_grpc_fuse.cpp.i

connect_grpc_fuse.s: connect_grpc_fuse.cpp.s
.PHONY : connect_grpc_fuse.s

# target to generate assembly for a file
connect_grpc_fuse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/connect_grpc_fuse.cpp.s
.PHONY : connect_grpc_fuse.cpp.s

unreliablefs.o: unreliablefs.c.o
.PHONY : unreliablefs.o

# target to build an object file
unreliablefs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/unreliablefs.c.o
.PHONY : unreliablefs.c.o

unreliablefs.i: unreliablefs.c.i
.PHONY : unreliablefs.i

# target to preprocess a source file
unreliablefs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/unreliablefs.c.i
.PHONY : unreliablefs.c.i

unreliablefs.s: unreliablefs.c.s
.PHONY : unreliablefs.s

# target to generate assembly for a file
unreliablefs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/unreliablefs.c.s
.PHONY : unreliablefs.c.s

unreliablefs_errinj.o: unreliablefs_errinj.c.o
.PHONY : unreliablefs_errinj.o

# target to build an object file
unreliablefs_errinj.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/unreliablefs_errinj.c.o
.PHONY : unreliablefs_errinj.c.o

unreliablefs_errinj.i: unreliablefs_errinj.c.i
.PHONY : unreliablefs_errinj.i

# target to preprocess a source file
unreliablefs_errinj.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/unreliablefs_errinj.c.i
.PHONY : unreliablefs_errinj.c.i

unreliablefs_errinj.s: unreliablefs_errinj.c.s
.PHONY : unreliablefs_errinj.s

# target to generate assembly for a file
unreliablefs_errinj.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/unreliablefs_errinj.c.s
.PHONY : unreliablefs_errinj.c.s

unreliablefs_ops.o: unreliablefs_ops.c.o
.PHONY : unreliablefs_ops.o

# target to build an object file
unreliablefs_ops.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/unreliablefs_ops.c.o
.PHONY : unreliablefs_ops.c.o

unreliablefs_ops.i: unreliablefs_ops.c.i
.PHONY : unreliablefs_ops.i

# target to preprocess a source file
unreliablefs_ops.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/unreliablefs_ops.c.i
.PHONY : unreliablefs_ops.c.i

unreliablefs_ops.s: unreliablefs_ops.c.s
.PHONY : unreliablefs_ops.s

# target to generate assembly for a file
unreliablefs_ops.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/unreliablefs_ops.c.s
.PHONY : unreliablefs_ops.c.s

wiscAFS.grpc.pb.o: wiscAFS.grpc.pb.cc.o
.PHONY : wiscAFS.grpc.pb.o

# target to build an object file
wiscAFS.grpc.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS_server.dir/build.make CMakeFiles/wiscAFS_server.dir/wiscAFS.grpc.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/wiscAFS.grpc.pb.cc.o
.PHONY : wiscAFS.grpc.pb.cc.o

wiscAFS.grpc.pb.i: wiscAFS.grpc.pb.cc.i
.PHONY : wiscAFS.grpc.pb.i

# target to preprocess a source file
wiscAFS.grpc.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS_server.dir/build.make CMakeFiles/wiscAFS_server.dir/wiscAFS.grpc.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/wiscAFS.grpc.pb.cc.i
.PHONY : wiscAFS.grpc.pb.cc.i

wiscAFS.grpc.pb.s: wiscAFS.grpc.pb.cc.s
.PHONY : wiscAFS.grpc.pb.s

# target to generate assembly for a file
wiscAFS.grpc.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS_server.dir/build.make CMakeFiles/wiscAFS_server.dir/wiscAFS.grpc.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/wiscAFS.grpc.pb.cc.s
.PHONY : wiscAFS.grpc.pb.cc.s

wiscAFS.pb.o: wiscAFS.pb.cc.o
.PHONY : wiscAFS.pb.o

# target to build an object file
wiscAFS.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS_server.dir/build.make CMakeFiles/wiscAFS_server.dir/wiscAFS.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/wiscAFS.pb.cc.o
.PHONY : wiscAFS.pb.cc.o

wiscAFS.pb.i: wiscAFS.pb.cc.i
.PHONY : wiscAFS.pb.i

# target to preprocess a source file
wiscAFS.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS_server.dir/build.make CMakeFiles/wiscAFS_server.dir/wiscAFS.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/wiscAFS.pb.cc.i
.PHONY : wiscAFS.pb.cc.i

wiscAFS.pb.s: wiscAFS.pb.cc.s
.PHONY : wiscAFS.pb.s

# target to generate assembly for a file
wiscAFS.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS_server.dir/build.make CMakeFiles/wiscAFS_server.dir/wiscAFS.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/wiscAFS.pb.cc.s
.PHONY : wiscAFS.pb.cc.s

wiscAFS_client.o: wiscAFS_client.cpp.o
.PHONY : wiscAFS_client.o

# target to build an object file
wiscAFS_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/wiscAFS_client.cpp.o
.PHONY : wiscAFS_client.cpp.o

wiscAFS_client.i: wiscAFS_client.cpp.i
.PHONY : wiscAFS_client.i

# target to preprocess a source file
wiscAFS_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/wiscAFS_client.cpp.i
.PHONY : wiscAFS_client.cpp.i

wiscAFS_client.s: wiscAFS_client.cpp.s
.PHONY : wiscAFS_client.s

# target to generate assembly for a file
wiscAFS_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS.dir/build.make CMakeFiles/wiscAFS.dir/wiscAFS_client.cpp.s
.PHONY : wiscAFS_client.cpp.s

wiscAFS_server.o: wiscAFS_server.cpp.o
.PHONY : wiscAFS_server.o

# target to build an object file
wiscAFS_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS_server.dir/build.make CMakeFiles/wiscAFS_server.dir/wiscAFS_server.cpp.o
.PHONY : wiscAFS_server.cpp.o

wiscAFS_server.i: wiscAFS_server.cpp.i
.PHONY : wiscAFS_server.i

# target to preprocess a source file
wiscAFS_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS_server.dir/build.make CMakeFiles/wiscAFS_server.dir/wiscAFS_server.cpp.i
.PHONY : wiscAFS_server.cpp.i

wiscAFS_server.s: wiscAFS_server.cpp.s
.PHONY : wiscAFS_server.s

# target to generate assembly for a file
wiscAFS_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wiscAFS_server.dir/build.make CMakeFiles/wiscAFS_server.dir/wiscAFS_server.cpp.s
.PHONY : wiscAFS_server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... wiscAFS"
	@echo "... wiscAFS_server"
	@echo "... conf.o"
	@echo "... conf.i"
	@echo "... conf.s"
	@echo "... connect_grpc_fuse.o"
	@echo "... connect_grpc_fuse.i"
	@echo "... connect_grpc_fuse.s"
	@echo "... unreliablefs.o"
	@echo "... unreliablefs.i"
	@echo "... unreliablefs.s"
	@echo "... unreliablefs_errinj.o"
	@echo "... unreliablefs_errinj.i"
	@echo "... unreliablefs_errinj.s"
	@echo "... unreliablefs_ops.o"
	@echo "... unreliablefs_ops.i"
	@echo "... unreliablefs_ops.s"
	@echo "... wiscAFS.grpc.pb.o"
	@echo "... wiscAFS.grpc.pb.i"
	@echo "... wiscAFS.grpc.pb.s"
	@echo "... wiscAFS.pb.o"
	@echo "... wiscAFS.pb.i"
	@echo "... wiscAFS.pb.s"
	@echo "... wiscAFS_client.o"
	@echo "... wiscAFS_client.i"
	@echo "... wiscAFS_client.s"
	@echo "... wiscAFS_server.o"
	@echo "... wiscAFS_server.i"
	@echo "... wiscAFS_server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

